mcc -T link:exe -o Cw6_Standalone -m -v Cw6 AutoAdjustGain Cw6LoadSubjInfo.m Cw6_BackEnd.m Cw6_MenuFunctions.m GUIChangeDetector_callback.m ...
GetExtinctions.m SendML2Cw6.m SetLaser.m cw6.fig loadCw6ConfigFile.m saveNIRSData.m validatesystem.m NIRS_timer_main_callback.m ...
PlotSDG.m localStopTimer.m plotmainwindow.m LaunchSplash.m LayOutFunction.m UITree_ted.m createDetTab.m createSrctab.m getjframe.m ...
uicomponent.m LoadSDG.m RegisterSubject.fig RegisterSubject.m SaveComments.m RealTimeFilterSetupMenu.fig...
RealTimeFilterSetupMenu.m processRTfunctions.m TimeDivMultiMenu.m ...
C:\Users\NIRSLab2\Desktop\CW6_control\Cw6\DisplayFcn\ShowAux.m...  
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_GLMKalmanFilter\Plot_GSSM.fig ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_GLMKalmanFilter\functioncallback_RT_GLMKalmanFilter ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_GLMKalmanFilter\Plot_GSSM.m ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_GLMKalmanFilter\addData_gssmGUI.m ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_GLMKalmanFilter\init_gssm2.m ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_GLMKalmanFilter\sendremote.m ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_BandPass\RT_BandPass.fig ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_BandPass\RT_BandPass.m...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_BandPass\Options_RT_BandPass.m ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_BandPass\functioncallback_RT_BandPass.m...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_MBLL\RT_kalmanfilter.m ...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_MBLL\functioncallback_RT_MBLL.m...
C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_gssm\functioncallback_RT_GSSM.m...
-a Splash.jpg -a cw6.cfg ...
-a C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_BandPass\Description_RT_BandPass.txt...
-a C:\Users\NIRSLab2\Desktop\CW6_control\RealTimeModules\RT_MBLL\Description_RT_MBLL.txt ...
-a C:\Users\NIRSLab2\Desktop\CW6_control\Cw6\RealTime\RealTimeFilterSetupMenu_activex1 ...
-a C:\Users\NIRSLab2\Desktop\CW6_control\Cw6\Auxillary\SelectAuxillary_activex1 ...
-a C:\Users\NIRSLab2\Desktop\CW6_control\Cw6\Auxillary\Eprime.jpg ...
-a C:\Users\NIRSLab2\Desktop\CW6_control\Cw6\Documentation\CW6_HELP.pdf ...
-a Description_RT_GLMKalmanFilter.txt ...
-d C:\Users\NIRSLab2\Desktop\CW6_control\StandAlone